### ISSUE TITLE
Allow consumer to specify Node version

### ISSUE THREAD

**Issue by tbeseda** [architect/action-build#2]
I'd like to build my project with Node 16 (or 12 or 18 😅).

like:
```yaml
      - name: Build App
        uses: architect/action-build@v3
        with:
          node-version: 16
```
